name: Test OpenAI API interaction

on:
  workflow_dispatch:  # Allows manual trigger
  release:            # Triggered on release
      types: [created]  # Specifically when a release is created
  # schedule:          # Uncomment below to enable a scheduled trigger
  #   - cron: '30 1 * * 5'  # Scheduled for 1:30am UTC (8:30pm EST) every Thursday

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install fastapi uvicorn httpx

    - name: Set up OpenAI API Key from GitHub secrets
      run: echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV

    - name: Start FastAPI server
      run: |
        uvicorn server:app --host 0.0.0.0 --port 8000 &

    - name: Wait for server to start
      run: sleep 10  # Wait for a while to ensure the server has started

    - name: Send request to server to interact with OpenAI API
      run: |
        curl -X 'POST' \
          'http://localhost:8000/generate_stream' \
          -H 'accept: text/event-stream' \
          -H 'Content-Type: application/json' \
          -d '{
          "inputs": "Translate the following English text to French: \'Hello, how are you?\'",
          "parameters": {
            "temperature": 0.7,
            "max_tokens": 100
          }
        }'
